
# Part 1: Action space
target_to_action_init = {
    'backpack': 'pick up', 'basket': 'get', 'bathtub': 'clean', 'bed': 'make',
    'blanket': 'fold', 'book': 'bring me', 'bookshelf': 'dust', 'bottle': 'recycle',
    'bowl': 'take to the sink', 'box': 'move', 'cabinet': 'wipe down', 'cart': 'push',
    'ceiling light': 'turn off', 'chair': 'push in', 'chest of drawers': 'wipe down',
    'clock': 'check', 'clothes': 'put away', 'coffee maker': 'turn on', 'couch': 'straighten the pillows on',
    'counter': 'wipe', 'cup': 'bring me', 'curtain': 'close', 'desk': 'clear',
    'dishwasher': 'unload', 'door': 'close', 'electric cooker': 'turn off', 'fan': 'turn on',
    'faucet': 'polish', 'hearth': 'sweep', 'keyboard': 'dust', 'lamp': 'turn on',
    'laptop': 'bring me', 'light': 'turn off', 'microwave': 'clean', 'mirror': 'wipe',
    'monitor': 'turn off', 'mouse': 'get', 'nightstand': 'tidy up', 'oven': 'clean',
    'pan': 'wash', 'pen': 'pick up', 'person': 'find', 'piano': 'dust',
    'picture': 'straighten', 'pillow': 'fluff', 'plant': 'water', 'plate': 'clear',
    'pot': 'put in the sink', 'refrigerator': 'wipe down', 'shelf': 'dust', 'shoe': 'put away',
    'shoe cabinet': 'organize', 'sideboard cabinet': 'wipe', 'sink': 'scrub',
    'sofa chair': 'push in', 'speaker': 'turn on', 'stool': 'move', 'table': 'wipe down',
    'tea table': 'clear', 'telephone': 'bring me', 'toilet': 'clean', 'towel': 'hang up',
    'toy': 'pick up', 'trashcan': 'empty', 'tray': 'clear', 'tv': 'dust',
    'tv stand': 'wipe', 'wall': 'inspect', 'washing machine': 'load', 'window': 'clean'
}

target_to_actions_signle_word = {
    'backpack': ['retrieve', 'get', 'move', 'open'],
    'basket': ['get', 'retrieve', 'empty', 'lift'],
    'bathtub': ['clean', 'fill', 'scrub', 'rinse'],
    'bed': ['make', 'straighten', 'inspect', 'smooth'],
    'blanket': ['fold', 'straighten', 'remove', 'spread'],
    'book': ['retrieve', 'bring me', 'close', 'open'],
    'bookshelf': ['dust', 'wipe', 'organize', 'browse'],
    'bottle': ['bring me', 'retrieve', 'clean', 'recycle'],
    'bowl': ['get', 'wash', 'fill', 'clean'],
    'box': ['move', 'open', 'empty', 'get'],
    'cabinet': ['wipe', 'open', 'close', 'reorganize'],
    'cart': ['push', 'pull', 'load', 'unload'],
    'ceiling light': ['deactivate', 'activate', 'replace', 'fix'],
    'chair': ['stow', 'remove', 'use', 'clean'],
    'chest of drawers': ['wipe', 'open', 'empty', 'close'],
    'clock': ['read', 'adjust', 'dust', 'straighten'],
    'clothes': ['stow', 'gather', 'fold', 'organize'],
    'coffee maker': ['activate', 'clean', 'deactivate', 'operate'],
    'couch': ['straighten', 'use', 'empty', 'clean'],
    'counter': ['wipe', 'clear', 'sanitize', 'clean'],
    'cup': ['bring me', 'get', 'fill', 'wash'],
    'curtain': ['close', 'open', 'adjust', 'replace'],
    'desk': ['clear', 'wipe', 'organize', 'dust'],
    'dishwasher': ['unload', 'load', 'activate', 'clean'],
    'door': ['close', 'open', 'disinfect', 'lock'],
    'electric cooker': ['deactivate', 'clean', 'activate', 'check'],
    'fan': ['activate', 'deactivate', 'dust', 'adjust'],
    'faucet': ['activate', 'deactivate', 'polish', 'disinfect'],
    'hearth': ['sweep', 'clean', 'inspect', 'clear'],
    'keyboard': ['dust', 'wipe', 'use', 'retrieve'],
    'lamp': ['activate', 'deactivate', 'dust', 'adjust'],
    'laptop': ['bring me', 'open', 'deactivate', 'use'],
    'light': ['deactivate', 'activate', 'toggle', 'check'],
    'microwave': ['clean', 'open', 'use', 'wipe'],
    'mirror': ['wipe', 'clean', 'polish', 'inspect'],
    'monitor': ['deactivate', 'clean', 'activate', 'retrieve'],
    'mouse': ['get', 'use', 'inspect', 'clean'],
    'nightstand': ['tidy up', 'clean', 'wipe', 'clear'],
    'oven': ['clean', 'open', 'activate', 'preheat'],
    'pan': ['wash', 'scrub', 'retrieve', 'get'],
    'pen': ['retrieve', 'get', 'bring me', 'use'],
    'person': ['approach', 'talk to', 'wave at', 'locate'],
    'piano': ['dust', 'play', 'clean', 'use'],
    'picture': ['straighten', 'dust', 'clean', 'remove'],
    'pillow': ['fluff', 'retrieve', 'bring me', 'remove'],
    'plant': ['water', 'move', 'get', 'trim'],
    'plate': ['clear', 'get', 'wash', 'stack'],
    'pot': ['wash', 'retrieve', 'clean', 'fetch'],
    'refrigerator': ['wipe', 'open', 'close', 'inventory'],
    'shelf': ['dust', 'empty', 'wipe', 'organize'],
    'shoe': ['stow', 'retrieve', 'bring me', 'get'],
    'shoe cabinet': ['organize', 'open', 'wipe', 'browse'],
    'sideboard cabinet': ['wipe', 'dust', 'open', 'clear'],
    'sink': ['scrub', 'clean', 'rinse', 'fill'],
    'sofa chair': ['stow', 'use', 'rotate', 'dust'],
    'speaker': ['activate', 'deactivate', 'adjust', 'connect to'],
    'stool': ['move', 'remove', 'wipe', 'take'],
    'table': ['wipe', 'clear', 'set', 'dust'],
    'tea table': ['clear', 'wipe', 'dust', 'move'],
    'telephone': ['bring me', 'answer', 'retrieve', 'clean'],
    'toilet': ['clean', 'flush', 'scrub', 'restock'],
    'towel': ['hang up', 'refold', 'change', 'bring me'],
    'toy': ['retrieve', 'stow', 'get', 'play with'],
    'trashcan': ['empty', 'reline', 'move', 'inspect'],
    'tray': ['clear', 'wipe', 'retrieve', 'bring me'],
    'tv': ['dust', 'activate', 'deactivate', 'clean'],
    'tv stand': ['wipe', 'clean', 'dust', 'organize'],
    'wall': ['inspect', 'paint', 'clean', 'touch'],
    'washing machine': ['load', 'unload', 'activate', 'empty'],
    'window': ['clean', 'open', 'close', 'polish']
}

target_to_actions_final = {
    'backpack': ['pick up', 'get', 'move', 'open'],
    'basket': ['get', 'pick up', 'empty', 'lift up'],
    'bathtub': ['clean', 'fill', 'scrub', 'rinse'],
    'bed': ['make', 'straighten', 'inspect', 'smooth'],
    'blanket': ['fold', 'straighten', 'remove', 'spread'],
    'book': ['pick up', 'bring me', 'close', 'open'],
    'bookshelf': ['dust', 'wipe down', 'organize', 'browse'],
    'bottle': ['bring me', 'pick up', 'clean', 'recycle'],
    'bowl': ['get', 'wash', 'fill', 'clean'],
    'box': ['move', 'open', 'empty', 'get'],
    'cabinet': ['wipe down', 'open', 'close', 'reorganize'],
    'cart': ['push', 'pull', 'load', 'unload'],
    'ceiling light': ['turn off', 'turn on', 'replace', 'fix'],
    'chair': ['push in', 'pull out', 'sit in', 'clean'],
    'chest of drawers': ['wipe down', 'open', 'empty', 'close'],
    'clock': ['read', 'adjust', 'dust', 'straighten'],
    'clothes': ['put away', 'pick up', 'fold', 'hang up'],
    'coffee maker': ['turn on', 'clean', 'turn off', 'operate'],
    'couch': ['straighten', 'sit on', 'empty', 'clean'],
    'counter': ['wipe', 'clean off', 'clear', 'sanitize'],
    'cup': ['bring me', 'get', 'fill', 'wash'],
    'curtain': ['close', 'open', 'adjust', 'replace'],
    'desk': ['clear', 'wipe down', 'organize', 'dust'],
    'dishwasher': ['unload', 'load', 'turn on', 'clean'],
    'door': ['close', 'open', 'disinfect', 'lock'],
    'electric cooker': ['turn off', 'clean', 'turn on', 'check'],
    'fan': ['turn on', 'turn off', 'dust', 'adjust'],
    'faucet': ['turn on', 'turn off', 'polish', 'disinfect'],
    'hearth': ['sweep', 'clean', 'inspect', 'clear'],
    'keyboard': ['dust', 'wipe', 'use', 'pick up'],
    'lamp': ['turn on', 'turn off', 'dust', 'adjust'],
    'laptop': ['bring me', 'open', 'turn off', 'use'],
    'light': ['turn off', 'turn on', 'toggle', 'check'],
    'microwave': ['clean', 'open', 'use', 'wipe down'],
    'mirror': ['wipe', 'clean', 'polish', 'inspect'],
    'monitor': ['turn off', 'clean', 'turn on', 'pick up'],
    'mouse': ['get', 'use', 'inspect', 'clean'],
    'nightstand': ['tidy up', 'clean', 'wipe down', 'clear off'],
    'oven': ['clean', 'open', 'turn on', 'preheat'],
    'pan': ['wash', 'scrub', 'pick up', 'get'],
    'pen': ['pick up', 'get', 'bring me', 'use'],
    'person': ['approach', 'talk to', 'wave at', 'locate'],
    'piano': ['dust', 'play', 'clean', 'sit at'],
    'picture': ['straighten', 'dust', 'clean', 'take down'],
    'pillow': ['fluff', 'pick up', 'bring me', 'remove'],
    'plant': ['water', 'move', 'get', 'trim'],
    'plate': ['clear', 'get', 'wash', 'stack'],
    'pot': ['wash', 'pick up', 'clean', 'fetch'],
    'refrigerator': ['wipe down', 'open', 'close', 'inventory'],
    'shelf': ['dust', 'empty', 'wipe', 'organize'],
    'shoe': ['put away', 'pick up', 'bring me', 'get'],
    'shoe cabinet': ['organize', 'open', 'wipe down', 'browse'],
    'sideboard cabinet': ['wipe', 'dust', 'open', 'clear off'],
    'sink': ['scrub', 'clean', 'rinse', 'fill'],
    'sofa chair': ['push in', 'sit in', 'rotate', 'dust'],
    'speaker': ['turn on', 'turn off', 'adjust', 'connect to'],
    'stool': ['move', 'pull out', 'wipe', 'take'],
    'table': ['wipe down', 'clear off', 'set', 'dust'],
    'tea table': ['clear', 'wipe', 'dust', 'move'],
    'telephone': ['bring me', 'answer', 'pick up', 'clean'],
    'toilet': ['clean', 'flush', 'scrub', 'restock'],
    'towel': ['hang up', 'refold', 'change', 'bring me'],
    'toy': ['pick up', 'put away', 'get', 'play with'],
    'trashcan': ['empty', 'reline', 'move', 'inspect'],
    'tray': ['clear', 'wipe', 'pick up', 'bring me'],
    'tv': ['dust', 'turn on', 'turn off', 'clean'],
    'tv stand': ['wipe', 'clean', 'dust off', 'organize'],
    'wall': ['inspect', 'paint', 'clean', 'touch'],
    'washing machine': ['load', 'unload', 'turn on', 'empty'],
    'window': ['clean', 'open', 'close', 'polish']
}

kujiale_target_actions = {
    'air conditioner': ['turn on', 'turn off', 'adjust', 'check'],
    'bag': ['open', 'close', 'empty', 'get'],
    'basin': ['wash', 'fill', 'rinse', 'clean'],
    'bathroom product': ['get', 'use', 'organize', 'check'],
    'bedding': ['straighten', 'change', 'fold', 'remove'],
    'bench': ['sit on', 'wipe', 'move', 'clear'],
    'bread machine': ['turn on', 'clean', 'use', 'open'],
    'built-in oven': ['preheat', 'clean', 'open', 'use'],
    'carpet': ['clean', 'vacuum', 'inspect', 'straighten'],
    'ceiling': ['inspect', 'clean', 'paint', 'check'],
    'chandelier': ['turn on', 'turn off', 'dust', 'clean'],
    'chopstick': ['get', 'wash', 'use', 'pair'],
    'closestool': ['flush', 'clean', 'scrub', 'close'],
    'cloth': ['wash', 'fold', 'unfold', 'get'],
    'computer': ['turn on', 'turn off', 'use', 'restart'],
    'cookware': ['wash', 'get', 'stow', 'organize'],
    'cosmetic': ['use', 'get', 'organize', 'open'],
    'cushion': ['fluff', 'straighten', 'get', 'clean'],
    'daily equipment': ['use', 'get', 'inspect', 'stow'],
    'decorative box': ['dust', 'open', 'move', 'get'],
    'dining table': ['set', 'clear', 'wipe', 'clean'],
    'door handle': ['clean', 'pull', 'disinfect', 'polish'],
    'doorsill': ['clean', 'sweep', 'wipe', 'inspect'],
    'electric appliance': ['turn on', 'turn off', 'unplug', 'check'],
    'entrance': ['clear', 'sweep', 'inspect', 'enter'],
    'floor': ['sweep', 'mop', 'clean', 'vacuum'],
    'floor lamp': ['turn on', 'turn off', 'adjust', 'dust'],
    'flower': ['water', 'trim', 'smell', 'get'],
    'food': ['prepare', 'eat', 'get', 'store'],
    'fork': ['get', 'wash', 'use', 'polish'],
    'fruit': ['wash', 'eat', 'get', 'peel'],
    'fridge': ['wipe', 'open', 'close', 'inventory'],
    'hardware decoration': ['polish', 'dust', 'inspect', 'straighten'],
    'induction cooker': ['turn on', 'turn off', 'wipe', 'use'],
    'kettle': ['fill', 'turn on', 'empty', 'clean'],
    'kitchenware': ['wash', 'organize', 'get', 'stow'],
    'knife': ['get', 'wash', 'use', 'sharpen'],
    'menorah': ['light', 'polish', 'dust', 'display'],
    'office supply': ['get', 'organize', 'use', 'stow'],
    'ornament': ['dust', 'straighten', 'get', 'inspect'],
    'other cooker': ['turn on', 'turn off', 'clean', 'use'],
    'other light': ['turn on', 'turn off', 'adjust', 'check'],
    'painting': ['straighten', 'dust', 'admire', 'remove'],
    'pet': ['feed', 'pet', 'find', 'play with'],
    'picture frame': ['dust', 'straighten', 'wipe', 'inspect'],
    'pillar': ['clean', 'inspect', 'decorate', 'wipe'],
    'range hood': ['turn on', 'turn off', 'clean', 'wipe'],
    'screen': ['turn on', 'turn off', 'clean', 'adjust'],
    'sculpture': ['dust', 'admire', 'move', 'inspect'],
    'sound': ['turn on', 'turn off', 'adjust', 'test'],
    'sofa': ['push in', 'sit in', 'rotate', 'dust'],
    'spoon': ['get', 'wash', 'use', 'polish'],
    'spotlight': ['turn on', 'turn off', 'adjust', 'focus'],
    'storage': ['open', 'organize', 'close', 'check'],
    'table lamp': ['turn on', 'turn off', 'adjust', 'dust'],
    'tablecloth': ['spread', 'straighten', 'clean', 'remove'],
    'tea set': ['use', 'wash', 'arrange', 'get'],
    'throw pillow': ['fluff', 'arrange', 'get', 'remove'],
    'television': ['turn on', 'turn off', 'dust', 'adjust'],
    'tooling': ['get', 'use', 'organize', 'inspect'],
    'vase': ['fill', 'empty', 'dust', 'get'],
    'wall decoration': ['straighten', 'dust', 'remove', 'inspect'],
    'wall light': ['turn on', 'turn off', 'clean', 'check'],
    'water cooler': ['use', 'refill', 'clean', 'check'],
    'water heater': ['turn on', 'turn off', 'adjust', 'check'],
    'water tap': ['turn off', 'adjust', 'check', 'clean'],
    'wine set': ['use', 'wash', 'arrange', 'get']
}

# Merge two dicts; duplicate keys are replaced by the latter
target_to_actions_final = target_to_actions_final | kujiale_target_actions

# New actions
kuajie_new1 = {'air purifier': ['turn on', 'turn off', 'adjust', 'clean'],
               'pendant': ['turn on', 'turn off', 'dust', 'adjust'],
}
target_to_actions_final = target_to_actions_final | kuajie_new1

kujiale_new2 = {'other furniture': ['move', 'clean', 'inspect', 'organize'],
               'stair': ['climb', 'descend', 'dust', 'clean'],
               'shower': ['turn on', 'turn off', 'adjust', 'clean'],}

target_to_actions_final = target_to_actions_final | kujiale_new2
if __name__ == '__main__':
    key_new = set(kujiale_target_actions.keys())
    key_old = set(target_to_actions_final.keys())
    intersection = key_new.intersection(key_old)
    print(f'Should be empty: -> intersection: {intersection}') # should be empty set
